=== Paagola/repo/src/ejercicio9/ejercicio9.dtd
<!ELEMENT catalogo (libro+)>
<!ELEMENT libro (dc:title, dc:creator, dc:publisher?, dc:date)>
<!ATTLIST libro id CDATA #REQUIRED>
<!ELEMENT dc:title (#PCDATA)>
<!ELEMENT dc:creator (#PCDATA)>
<!ELEMENT dc:publisher (#PCDATA)>
<!ELEMENT dc:date (#PCDATA)>

=== Paagola/repo/src/ejercicio9/ejercicio9.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogo SYSTEM "ejercicio9.dtd">
<catalogo xmlns:dc="http://purl.org/dc/elements/1.1/">
    <libro id="1">
        <dc:title>El Quijote</dc:title>
        <dc:creator>Miguel de Cervantes</dc:creator>
        <dc:publisher>Editorial Clásicos</dc:publisher>
        <dc:date>1605</dc:date>
    </libro>
    <libro id="2">
        <dc:title>Cien años de soledad</dc:title>
        <dc:creator>Gabriel Garcia Márquez</dc:creator>
        <dc:date>1967</dc:date>
        <dc:publisher>Editorial Sudamericana</dc:publisher>
    </libro>
</catalogo>
